---
- name: Configure automation controller
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: "Create jira api credential type"
      awx.awx.credential_type:
        name: "Jira"
        description: "Credentials type for jira"
        kind: "cloud"
        inputs:
          fields:
            - id: "username"
              type: "string"
              label: "username"
              multiline: false
            - id: "password"
              type: "string"
              label: "password"
              secret: true
              multiline: false
            - id: "url"
              type: "string"
              label: "url"
              secret: false
              multiline: false
        injectors:
          extra_vars:
            jira_username: "{% raw -%}{{ username }}{% endraw -%}"
            jira_password: "{% raw -%}{{ password }}{% endraw -%}"
            jira_url: "{% raw -%}{{ url }}{% endraw -%}"
        state: present
        controller_config_file: "controller.cfg"

    - name: "Create jira api credential"
      awx.awx.credential:
        name: "Jira onboarding"
        organization: "Default"
        state: "present"
        credential_type: "Jira"
        inputs:
          username: "{{ lookup('env', 'TF_VAR_jira_onboarding_username') }}"
          password: "{{ lookup('env', 'TF_VAR_jira_onboarding_password') }}"
          url: "{{ lookup('env', 'TF_VAR_jira_url') }}"
        controller_config_file: "controller.cfg"

    - name: "Create aap api credential type"
      awx.awx.credential_type:
        name: "Aap"
        description: "Credentials type for aap"
        kind: "cloud"
        inputs:
          fields:
            - id: "username"
              type: "string"
              label: "username"
              multiline: false
            - id: "password"
              type: "string"
              label: "password"
              secret: true
              multiline: false
            - id: "url"
              type: "string"
              label: "url"
              secret: false
              multiline: false
        injectors:
          extra_vars:
            aap_username: "{% raw -%}{{ username }}{% endraw -%}"
            aap_password: "{% raw -%}{{ password }}{% endraw -%}"
            aap_url: "{% raw -%}{{ url }}{% endraw -%}"
        state: present
        controller_config_file: "controller.cfg"

    - name: "Create aap api credential"
      awx.awx.credential:
        name: "Aap onboarding"
        organization: "Default"
        state: "present"
        credential_type: "Aap"
        inputs:
          username: "{{ lookup('env', 'TF_VAR_aap_username') }}"
          password: "{{ lookup('env', 'TF_VAR_aap_password') }}"
          url: "{{ lookup('env', 'TF_VAR_aap_url') }}"
        controller_config_file: "controller.cfg"

    - name: "Add project for jira self-service"
      awx.awx.project:
        name: "Self-service"
        description: "Jira self-service integration."
        organization: "Default"
        state: "present"
        scm_type: "git"
        scm_url: "https://gitlab.com/jmhbnz/self-service-demo.git"
        controller_config_file: "controller.cfg"
        scm_update_on_launch: false

    - name: "Add job template for dummy onboarding tasks"
      awx.awx.job_template:
        name: "Onboarding dummy task"
        organization: "Default"
        state: "present"
        description: "Job template to complete an onboarding task."
        project: "Self-service"
        inventory: "Localhost"
        playbook: "5-jira-workflow-onboarding/dummy-onboarding-playbook.yaml"
        survey_enabled: false
        ask_variables_on_launch: true
        controller_config_file: "controller.cfg"

    - name: "Add job template for request validation"
      awx.awx.job_template:
        name: "Validate onboarding request"
        organization: "Default"
        state: "present"
        description: "Job template to validate an onboarding request."
        project: "Self-service"
        inventory: "Localhost"
        playbook: "5-jira-workflow-onboarding/validate-onboarding-request.yaml"
        survey_enabled: false
        ask_variables_on_launch: false
        controller_config_file: "controller.cfg"

    - name: "Add job template for jira comment"
      awx.awx.job_template:
        name: "Jira comment"
        organization: "Default"
        state: "present"
        description: ""
        project: "Self-service"
        inventory: "Localhost"
        playbook: "5-jira-workflow-onboarding/comment-jira-issue-api.yaml"
        survey_enabled: false
        ask_credential_on_launch: true
        ask_variables_on_launch: true
        controller_config_file: "controller.cfg"

    - name: "Add job template for jira assign"
      awx.awx.job_template:
        name: "Jira assign"
        organization: "Default"
        state: "present"
        description: ""
        project: "Self-service"
        inventory: "Localhost"
        playbook: "5-jira-workflow-onboarding/assign-jira-issue-api.yaml"
        survey_enabled: false
        ask_credential_on_launch: true
        ask_variables_on_launch: true
        controller_config_file: "controller.cfg"

    - name: "Add job template for jira transition"
      awx.awx.job_template:
        name: "Jira transition"
        organization: "Default"
        state: "present"
        description: ""
        project: "Self-service"
        inventory: "Localhost"
        playbook: "5-jira-workflow-onboarding/transition-jira-issue-api.yaml"
        survey_enabled: false
        ask_credential_on_launch: true
        ask_variables_on_launch: true
        controller_config_file: "controller.cfg"

    - name: "Create a workflow job template for onboarding"
      awx.awx.workflow_job_template:
        controller_config_file: "controller.cfg"
        name: "Onboarding"
        inventory: "Localhost"
        destroy_current_schema: true
        ask_variables_on_launch: true
        allow_simultaneous: true

    - name: "Create workflow node for done transition"
      awx.awx.workflow_job_template_node:
        identifier: "Done transition"
        unified_job_template: "Jira transition"
        workflow_job_template: "Onboarding"
        extra_data:
          jira_transition: "41"
        credentials:
          - "Jira onboarding"
        controller_config_file: "controller.cfg"

    - name: "Create workflow node for onboarding done comment"
      awx.awx.workflow_job_template_node:
        identifier: "Completed comment"
        unified_job_template: "Jira comment"
        workflow_job_template: "Onboarding"
        credentials:
          - "Jira onboarding"
        extra_data:
          jira_comment: "Onboarding workflow completed! New team member has been setup with requested role ✅"
        controller_config_file: "controller.cfg"
        all_parents_must_converge: true
        success_nodes: "Done transition"

    - name: "Create workflow node for onboarding dummy task 1"
      awx.awx.workflow_job_template_node:
        identifier: "Create openshift namespace"
        unified_job_template: "Onboarding dummy task"
        workflow_job_template: "Onboarding"
        controller_config_file: "controller.cfg"
        extra_data:
          wait_seconds: 30
        success_nodes:
          - "Completed comment"

    - name: "Create workflow node for onboarding dummy task 2"
      awx.awx.workflow_job_template_node:
        identifier: "Password vault access"
        unified_job_template: "Onboarding dummy task"
        workflow_job_template: "Onboarding"
        controller_config_file: "controller.cfg"
        extra_data:
          wait_seconds: 15
        success_nodes:
          - "Completed comment"

    - name: "Create workflow node for onboarding dummy task 3"
      awx.awx.workflow_job_template_node:
        identifier: "Assign active directory groups"
        unified_job_template: "Onboarding dummy task"
        workflow_job_template: "Onboarding"
        controller_config_file: "controller.cfg"
        extra_data:
          wait_seconds: 30
        success_nodes:
          - "Completed comment"

    - name: "Create workflow node for onboarding dummy task 4"
      awx.awx.workflow_job_template_node:
        identifier: "Docker daemon access on admin server"
        unified_job_template: "Onboarding dummy task"
        workflow_job_template: "Onboarding"
        controller_config_file: "controller.cfg"
        extra_data:
          wait_seconds: 15
        success_nodes:
          - "Completed comment"

    - name: "Create workflow node for onboarding comment"
      awx.awx.workflow_job_template_node:
        identifier: "Assigned comment"
        unified_job_template: "Jira comment"
        workflow_job_template: "Onboarding"
        credentials:
          - "Jira onboarding"
        extra_data:
          jira_comment: "This issue has been picked up by onboarding bot :)  You can track my progress here: https://aap.apps.rosa-xjm4v.nx1c.p1.openshiftapps.com/#/jobs?job.name__icontains=onboarding&job.or__type=workflow_job"
        controller_config_file: "controller.cfg"
        success_nodes:
          - "Create openshift namespace"
          - "Password vault access"
          - "Assign active directory groups"
          - "Docker daemon access on admin server"

    - name: "Create workflow node for onboarding declined"
      awx.awx.workflow_job_template_node:
        identifier: "Declined comment"
        unified_job_template: "Jira comment"
        workflow_job_template: "Onboarding"
        credentials:
          - "Jira onboarding"
        extra_data:
          jira_comment: "Onboarding user into requested role was not approved."
        controller_config_file: "controller.cfg"

    - name: "Create workflow node for in progress transition"
      awx.awx.workflow_job_template_node:
        identifier: "In progress transition"
        unified_job_template: "Jira transition"
        workflow_job_template: "Onboarding"
        extra_data:
          jira_transition: "11"
        credentials:
          - "Jira onboarding"
        controller_config_file: "controller.cfg"
        success_nodes:
          - "Assigned comment"

    - name: "Create workflow node for onboarding assign"
      awx.awx.workflow_job_template_node:
        identifier: "Assign"
        unified_job_template: "Jira assign"
        workflow_job_template: "Onboarding"
        credentials:
          - "Jira onboarding"
        controller_config_file: "controller.cfg"
        success_nodes:
          - "In progress transition"

    - name: "Approval node based on role"
      awx.awx.workflow_job_template_node:
        identifier: "Approval"
        workflow_job_template: "Onboarding"
        approval_node:
          description: "Should user be setup with role?"
          name: "Approval"
          timeout: 3600
        controller_config_file: "controller.cfg"

    - name: "Link approval node"
      awx.awx.workflow_job_template_node:
        identifier: "Approval"
        workflow_job_template: "Onboarding"
        controller_config_file: "controller.cfg"
        success_nodes:
          - "Assign"
        failure_nodes:
          - "Declined comment"

    - name: "Create workflow node for approval required comment"
      awx.awx.workflow_job_template_node:
        identifier: "Approval comment"
        unified_job_template: "Jira comment"
        workflow_job_template: "Onboarding"
        credentials:
          - "Jira onboarding"
        extra_data:
          jira_comment: "Approval required for this request: https://aap.apps.rosa-xjm4v.nx1c.p1.openshiftapps.com/#/workflow_approvals?workflow_approvals.status__startswith=pending"
        controller_config_file: "controller.cfg"
        success_nodes: "Approval"

    - name: "Create workflow node for request validation"
      awx.awx.workflow_job_template_node:
        identifier: "Validate"
        unified_job_template: "Validate onboarding request"
        workflow_job_template: "Onboarding"
        controller_config_file: "controller.cfg"
        success_nodes:
         - "Assign"
        failure_nodes:
          - "Approval comment"

    - name: "Add job template for approving a workflow"
      awx.awx.job_template:
        name: "Approve workflow"
        organization: "Default"
        state: "present"
        description: "Job template to approve a pending workflow."
        project: "Self-service"
        inventory: "Localhost"
        credentials:
          - "Aap onboarding"
        playbook: "5-jira-workflow-onboarding/approve-aap-workflow.yaml"
        survey_enabled: false
        ask_variables_on_launch: false
        controller_config_file: "controller.cfg"