---
- name: Dummy playbook representing an onboarding step
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: "Wait for a provided amount of time"
      ansible.builtin.pause:
        seconds: "{{ wait_seconds }}"

    - name: "Dummy onboarding"
      ansible.builtin.debug:
        msg: "Completed sucessfully"
