# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml

include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml

stages:
  - validate
  - test
  - build
  - create-vm
  - deploy
  - destroy

before_script:
  - export TF_ROOT="0-deploy-demo-infra"

fmt:
  extends: .terraform:fmt
  needs: []
  only:
    changes:
      - 0-deploy-demo-infra/*

validate:
  extends: .terraform:validate
  needs: []
  only:
    changes:
      - 0-deploy-demo-infra/*

build:
  extends: .terraform:build
  only:
    changes:
      - 0-deploy-demo-infra/*

create-vm:
  script:
    - curl -X POST -H "Content-Type: application/json" -d '{"extra_vars": {"var1": "value1"}}' -H "Authorization: Bearer <AWX_TOKEN>" <AWX_URL>/api/v2/job_templates/<AWX_JOB_TEMPLATE_ID>/launch/
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual


deploy:
  extends: .terraform:deploy
  environment:
    name: development
  when: manual
  allow_failure: true
  only:
    changes:
      - 0-deploy-demo-infra/*

destroy:
  extends: .terraform:destroy
  when: manual
  allow_failure: true
  only:
    changes:
      - 0-deploy-demo-infra/*
