# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml

include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml

stages:
  - validate
  - test
  - build
  - create-vm
  - deploy
  - cleanup

before_script:
  - export TF_ROOT="0-deploy-demo-infra"

fmt:
  extends: .terraform:fmt
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - 0-deploy-demo-infra/*

validate:
  extends: .terraform:validate
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - 0-deploy-demo-infra/*

build:
  extends: .terraform:build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - 0-deploy-demo-infra/*

create-vm:
  script:
    - >
        curl -X POST -k -H "Content-Type: application/json"
        -d '{"extra_vars": {"region": "$region", "instance_type": "$instance_type", "image_id", "$image_id" }}'
        -H "Authorization: Bearer $TF_VAR_aap_token"
        https://controller.rhdemo.win/api/v2/job_templates/9/launch/
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  variables:
    - region:
        prompt: "Enter the region for ec2 instance"
        default: "ap-southeast-2"
    - instance_type:
        prompt: "Enter the desired ec2 instance type"
        default: "t2.micro"
    - image_id:
        prompt: "Enter the ec2 machine image id"
        default: "ami-0b4ee18dc73d90a7b"

deploy:
  extends: .terraform:deploy
  environment:
    name: development
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - 0-deploy-demo-infra/*
      when: manual

destroy:
  extends: .terraform:destroy
  when: manual
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - 0-deploy-demo-infra/*
      when: manual
