---
- name: Close a jira issue via api
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: "Close a jira issue via api"
      ansible.builtin.uri:
        url: "https://big-emus-lead-124-248-138-127.loca.lt/rest/api/2/issue/{{ jira_issue }}/transitions"
        user: "{{ jira_username }}"
        password: "{{ jira_password }}"
        method: "POST"
        body:
          transition:
            id: 21
        force_basic_auth: true
        status_code: 204
        body_format: "json"
      register: results

    - name: "Output jira close results"
      ansible.builtin.debug:
        var: results.status
