---
- name: Configure automation controller
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: "Create jira api credential type"
      awx.awx.credential_type:
        name: "Jira"
        description: "Credentials type for jira"
        kind: "cloud"
        inputs:
          fields:
            - id: "username"
              type: "string"
              label: "username"
              multiline: false
            - id: "password"
              type: "string"
              label: "password"
              secret: true
              multiline: false
            - id: "url"
              type: "string"
              label: "url"
              secret: false
              multiline: false
        injectors:
          extra_vars:
            jira_username: "{% raw -%}{{ username }}{% endraw -%}"
            jira_password: "{% raw -%}{{ password }}{% endraw -%}"
            jira_url: "{% raw -%}{{ url }}{% endraw -%}"
        state: present
        controller_config_file: "controller.cfg"

    - name: "Create jira api credential"
      awx.awx.credential:
        name: "Jira onboarding"
        organization: "Default"
        state: "present"
        credential_type: "Jira"
        inputs:
          username: "{{ lookup('env', 'TF_VAR_jira_onboarding_username') }}"
          password: "{{ lookup('env', 'TF_VAR_jira_onboarding_password') }}"
          url: "{{ lookup('env', 'TF_VAR_jira_url') }}"
        controller_config_file: "controller.cfg"

    - name: "Add project for jira self-service"
      awx.awx.project:
        name: "Self-service"
        description: "Jira self-service integration."
        organization: "Default"
        state: "present"
        scm_type: "git"
        scm_url: "https://gitlab.com/jmhbnz/self-service-demo.git"
        controller_config_file: "controller.cfg"
        scm_update_on_launch: false

    - name: "Add job template for vault onboarding"
      awx.awx.job_template:
        name: "Onboarding - Vault"
        organization: "Default"
        state: "present"
        description: "Job template to create an aws ec2 instance."
        project: "Self-service"
        inventory: "Localhost"
        playbook: "1-ansible-automation-platform/deploy-ec2-native.yaml"
        credential: "Amazon Web Services"
        survey_enabled: false
        ask_variables_on_launch: false
        controller_config_file: "controller.cfg"

    - name: "Add job template for jira comment"
      awx.awx.job_template:
        name: "Jira comment"
        organization: "Default"
        state: "present"
        description: ""
        project: "Self-service"
        inventory: "Localhost"
        playbook: "5-jira-workflows/comment-jira-issue-api.yaml"
        survey_enabled: false
        ask_credential_on_launch: true
        ask_variables_on_launch: true
        controller_config_file: "controller.cfg"

    - name: "Add job template for jira assign"
      awx.awx.job_template:
        name: "Jira assign"
        organization: "Default"
        state: "present"
        description: ""
        project: "Self-service"
        inventory: "Localhost"
        playbook: "5-jira-workflows/assign-jira-issue-api.yaml"
        survey_enabled: false
        ask_credential_on_launch: true
        ask_variables_on_launch: true
        controller_config_file: "controller.cfg"

    - name: "Add job template for jira close"
      awx.awx.job_template:
        name: "Jira close"
        organization: "Default"
        state: "present"
        description: ""
        project: "Self-service"
        inventory: "Localhost"
        playbook: "5-jira-workflows/close-jira-issue-api.yaml"
        survey_enabled: false
        ask_credential_on_launch: true
        ask_variables_on_launch: false
        controller_config_file: "controller.cfg"

    - name: "Create a workflow job template for onboarding"
      awx.awx.workflow_job_template:
        controller_config_file: "controller.cfg"
        name: "Onboarding"
        inventory: "Localhost"
        destroy_current_schema: true
        ask_variables_on_launch: true
        ask_credential_on_launch: true

    - name: "Create workflow node for onboarding assign"
      awx.awx.workflow_job_template_node:
        identifier: "Assign"
        unified_job_template: "Jira assign"
        workflow_job_template: "Onboarding"
        credentials:
          - "Jira onboarding"
        controller_config_file: "controller.cfg"

    - name: "Create workflow node for onboarding comment"
      awx.awx.workflow_job_template_node:
        identifier: "Assigned comment"
        unified_job_template: "Jira comment"
        workflow_job_template: "Onboarding"
        credentials:
          - "Jira onboarding"
        extra_data:
          jira_comment: "This issue has been picked up by onboarding bot :)"
        controller_config_file: "controller.cfg"
