#+TITLE: Deploy keycloak via operator
#+AUTHOR: James Blair <jablair@redhat.com>
#+DATE: 13th November 2022

In order to demonstrate the full capabilities of the [[https://www.ansible.com/products/automation-platform][Ansible Automation Platform]] we need to have an identity and access management platform in place. For this capability we will use [[https://www.keycloak.org/][Keycloak]] the open source upstream for [[https://access.redhat.com/products/red-hat-single-sign-on][Red Hat Single Sign On]].

With Keycloack we can add authentication to applications and secure services with minimum effort. Keycloak provides user federation, strong authentication, user management, fine-grained authorization, and more.


* Deploy the keycloak operator

Our first step for deploying keycloak is to subscribe to the new [[https://quarkus.io/][Quarkus]] based [[https://github.com/keycloak/keycloak/tree/main/operator][keycloak-operator]]. We can create a new kubernetes ~namespace~ called ~keycloak~ and subscribe by running the following:

#+NAME: Deploy keycloak operator
#+begin_src tmate
# Create namespace for keycloak
oc new-project keycloak

# Create the operator subscription yaml
cat << EOF > keycloak-operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: keycloak
spec:
  channel: fast
  installPlanApproval: Automatic
  name: keycloak-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: keycloak-operator.v20.0.1
EOF

# Apply the operator subscription yaml
oc apply --filename keycloak-operator.yaml
#+end_src


* Deploy keycloak

Once the keycloak operator is running we can create an instance of keycloak using the [[https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/][custom resource definition]] that our newly deployed operator is watching for. Run the commands below to create and apply the custom resource:

Note: Substitute your openshift hostname into the template below as appropriate.

#+NAME: Deploy keycloak operator
#+begin_src tmate
# Create the custom resource yaml
cat << EOF > keycloak.yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: demo-keycloak
  namespace: keycloak
spec:
  hostname:
    admin: demo-keycloak.apps.rosa-5xmg9.ljce.p1.openshiftapps.com
    hostname: demo-keycloak.apps.rosa-5xmg9.ljce.p1.openshiftapps.com
  http:
    httpEnabled: true
    httpPort: 8080
    httpsPort: 8443
    tlsSecret: demo-tls-secret
  ingress:
    enabled: true
  instances: 1
EOF

# Apply the resource
oc apply --filename keycloak.yaml
#+end_src
