---
- name: Create a jira issue via api
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: "Create jira issue via api"
      ansible.builtin.uri:
        url: "{{ jira_url }}/rest/api/2/issue/"
        user: "{{ jira_username }}"
        password: "{{ jira_password }}"
        method: "POST"
        body:
          fields:
            project:
              key: "PLAT"
            issuetype:
              name: "Task"
            summary: "Drift detected for instance"
        force_basic_auth: true
        status_code: 201
        body_format: "json"
      register: results

    - name: "Output jira issue creation results"
      ansible.builtin.debug:
        var: results.json
