---
- name: Comment on a jira issue via api
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: "Output supplied comment to logs"
      debug:
        var: jira_comment

    - name: "Comment on a jira issue via api"
      ansible.builtin.uri:
        url: "{{ jira_url }}/rest/api/2/issue/{{ jira_issue }}/comment"
        user: "{{ jira_username }}"
        password: "{{ jira_password }}"
        method: "POST"
        body:
          body: "{{ jira_comment }}"
        force_basic_auth: true
        status_code: 201
        body_format: "json"
      register: results

    - name: "Output jira comment creation results"
      ansible.builtin.debug:
        var: results.json
