---
- name: Transition a jira issue via api
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: "Transition a jira issue via api"
      ansible.builtin.uri:
        url: "{{ jira_url }}/rest/api/2/issue/{{ jira_issue }}/transitions"
        user: "{{ jira_username }}"
        password: "{{ jira_password }}"
        method: "POST"
        body:
          transition:
            id: "{{ jira_transition }}"
        force_basic_auth: true
        status_code: 204
        body_format: "json"
      register: results

    - name: "Output jira transition results"
      ansible.builtin.debug:
        var: results.status
