---
- name: Create a rhel aws ec2 instance
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create a rhel aws ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ tags_purpose }}-ec2-instance"
        key_name: "{{ lookup('env', 'key_pair') | default('rhel-demo-dev-linux-ap-southeast-2') }}"
        vpc_subnet_id: "subnet-000af6e79d9951160"
        instance_type: "{{ instance_type.split(' ')[0] | default('t2.micro') }}"
        security_group: "default"
        region: "{{ region.split(' ')[0] | default('ap-southeast-2') }}"
        network:
          assign_public_ip: false
        image_id: "ami-0b4ee18dc73d90a7b"
        wait: true
        tags:
          purpose: "{{ tags_purpose }}"
