---
- name: Create an rhel ec2 instance
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Create the EC2 instance
      amazon.aws.ec2_instance:
        name: "demo-ec2-instance"
        key_name: "{{ lookup('env', 'key_pair') }}"
        vpc_subnet_id: "{{ lookup('env', 'subnet_id') }}"
        instance_type: "{{ lookup('env', 'instance_type') }}"
        security_group: "default"
        region: "{{ lookup('env', 'region') }}"
        network:
          assign_public_ip: false
        image_id: "{{ lookup('env', 'image_id') }}"
        wait: yes
        tags:
          type: "webserver"
